version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - DATA_DIR=/app/backend/data
      - local_files_only=False
     # - WEBUI_AUTH=false
     # - WEBUI_NAME=SampleKeyword
      - WEBUI_URL=http://0.0.0.0:3000
     # - GLOBAL_LOG_LEVEL="DEBUG"
    deploy:
      restart_policy:
        condition: always
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./ollama:/root/.ollama
      - ./data:/app/backend/data

volumes:
  ollama:
    driver: local
  open-webui:
    driver: local
