#https://github.com/iot-salzburg/gpu-jupyter
#Use .env file to store token. Ensure permissions for folder match running containers. 
version: "3.8"
services:
  gpu-jupyter:
    container_name: gpu-jupyter
    image: cschranz/gpu-jupyter:v1.6_cuda-11.8_ubuntu-22.04
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    ports:
      - 8848:8888
    volumes:
      - ${PWD}/data:/home/jovyan/work
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
      NB_UID: ${JUPYTER_UID:-1000}
      NB_GID: ${JUPYTER_GID:-1000}
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
    user: "root"
    restart: always
